version: '2'
services:
  sam-postgres-db:
    image: postgres:10.5-alpine
    container_name: sam-postgres-db
    environment:
      - POSTGRES_PASSWORD=cs399p41testdb
    ports:
      - '5432:5432'
    networks:
      sqlnet:
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        
networks:
  sqlnet: